version: 2
updates:
  # Maintain dependencies for github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "daily"
    labels:
      - "dependency"
    commit-message:
      prefix: "ci(github action dependencies)"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "daily"
    labels:
      - "dependency"
    commit-message:
      prefix: "fix(npm dependencies)"

  # Maintain dependencies for Composer
  - package-ecosystem: "composer"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "daily"
    labels:
      - "dependency"
    commit-message:
      prefix: "fix(composer dependencies)"
