name: "Continuous Integration"

on:
  push:
    branches:
      - 'develop'

jobs:
  docker:
    name: "Build Docker Image"
    runs-on: ubuntu-latest
    steps:
      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v3

      - name: "Set up Docker Build"
        uses: docker/setup-buildx-action@v3

      - name: "Login to Docker Hub"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Build and push"
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: indemnity83/lapse:latest
