name: "PR Check"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  contents: read
  pull-requests: read

jobs:

  validate-pr-title:
    name: "Validate Title"
    runs-on: ubuntu-latest
    steps:
      - name: "Check Title"
        uses: amannn/action-semantic-pull-request@v5
        with:
          requireScope: false
          wip: true

  pr-labeler:
    name: "Label PR"
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v4
